name: Withdraw, Predict, & Autobet
# This workflow is triggered on a schedule and manually

on:    
  workflow_dispatch: # Manually trigger the workflow

  schedule:
  - cron: '0 5 * * *'  # Runs once every day at 5:00 AM UTC (8:00 AM EAT +3)

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v2 

      # pick .env variables from github secrets
      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "BETIKA_PROFILE_ID=${{ secrets.BETIKA_PROFILE_ID }}" >> $GITHUB_ENV
          echo "BETIKA_TOKEN=${{ secrets.BETIKA_TOKEN }}" >> $GITHUB_ENV

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Withdraw
        run: python withdraw.py

      - name: Predict & Autobet
        run: python predict_2.py

