name: predict & Autobet

on:    
  workflow_dispatch: # Manually trigger the workflow

  schedule:
     - cron: '0 15-23/3 * * *'  # Runs every 3 hours from 15:00 to 21:00
     - cron: '0 0 * * *'        # Runs at 00:00
concurrency:
  group: continuous-job
  cancel-in-progress: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v2 
      
      # pick .env variables from github secrets
      - name: Set environment variables
        run: |
          echo "REDIS_HOSTNAME=${{ secrets.REDIS_HOSTNAME }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_SSL=${{ secrets.REDIS_SSL }}" >> $GITHUB_ENV
          echo "BETIKA_PROFILE_ID=${{ secrets.BETIKA_PROFILE_ID }}" >> $GITHUB_ENV
          echo "BETIKA_TOKEN=${{ secrets.BETIKA_TOKEN }}" >> $GITHUB_ENV
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Predict & Autobet 
        run: python daemons.py
          