name: Predict
# This workflow is triggered on a schedule and manually

on:    
  workflow_dispatch: # Manually trigger the workflow

  schedule:
    - cron: '0 3,9 * * *'  # Runs at 3:00am and 9:00am UTC (6:00am and 12:00pm EAT)

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v2 

      # pick .env variables from github secrets
      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}" >> $GITHUB_ENV

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Predict Ai
        run: python predict_ai.py


