name: Update Results
# This workflow is triggered on a schedule and manually

on:    
  workflow_dispatch: # Manually trigger the workflow

  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (e.g., 00:00, 06:00, 12:00, 18:00 UTC)

# Ensures only one workflow instance runs at a time by canceling the previous run
concurrency:
  group: run-forever
  cancel-in-progress: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v2 

      # pick .env variables from github secrets
      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Results
        run: python results.py
